### ISSUE TITLE
FTMC

### ISSUE THREAD

**Issue by Pfupferino** [emilsvennesson/kodi-viaplay#10]
Hi

it seems that your addon is not working with FTMC. I downloaded your latest version today and got following information:
Version 1.0.7
-> This version is deprecated. New versions are available for Kodi Krypton or later
The dependency on xbmc.python version 2.25.0 could not be satisfaction

My system is an Asus Tinker board
OS: Android 6.0.1 API level 23 (Kernel: Linux 3.10.0)
FTMC Built: 16.2-29 Git:2017-06-04-9df4378-dirty
compiled: 2017-06-04

**Comment by emilsvennesson** [comment]
Hi!

I'm not quite sure what FTMC is to be honest, but it seems to be based off an old version of Kodi that is no longer supported. In order to get Viaplay working right now, you'll need to use the Kodi 18 nightlies, inputstream.adaptive with the Widevine library in place as well as kodi-viaplay from git.

**Comment by Pfupferino** [comment]
Hi

I thank you for your feedback. I found FTMC here: https://www.ossblog.org/running-kodi-asus-tinker-board/
 and the advantage is that I can use accelerate the output and the movies are more smoth as with Kodi.
I also installed Kodi and your Viaplay add on is working fine:-).
